Vagrant.configure("2") do |config|
  config.vm.define "Ubuntu" do |ubuntu|
    ubuntu.vm.box = "hashicorp/bionic64"
    ubuntu.vm.hostname = "Ubuntu-vm"
    ubuntu.vm.provider "virtualbox" do |v|
      v.name = "ubuntu_vm"
    end
    ubuntu.vm.network "public_network", ip: "192.168.1.209", bridge: 'Intel(R) Wireless-AC 9560 160MHz'
  end
end
