Vagrant.configure("2") do |config|

  config.vm.define "Kube_master" do |master|
    master.vm.box = "hashicorp/bionic64"
    master.vm.hostname = "Kube-master"
    master.vm.provider "virtualbox" do |v|
      v.name = "Kube_master"
      v.customize ["modifyvm", :id, "--ioapic", "on"]
      v.customize ["modifyvm", :id, "--memory", "4096"]
      v.customize ["modifyvm", :id, "--cpus", "4"]
    end
    master.vm.provision "docker" do |d|
    end
    master.vm.provision :shell, path: "bootstrap.sh"
    master.vm.network "public_network", ip: "192.168.1.208", bridge: 'Intel(R) Wireless-AC 9560 160MHz'
  end

  # config.vm.define "Kube_node1" do |node1|
  #   node1.vm.box = "hashicorp/bionic64"
  #   node1.vm.hostname = "Kube-node1"
  #   node1.vm.provider "virtualbox" do |v|
  #     v.name = "Kube_node1"
  #   end
  #   node1.vm.provision "docker" do |d|
  #   end
  #   node1.vm.provision :shell, path: "bootstrap.sh"
  #   node1.vm.network "public_network", ip: "192.168.1.209", bridge: 'Intel(R) Wireless-AC 9560 160MHz'
  # end
  #
  # config.vm.define "Kube_node2" do |node2|
  #   node2.vm.box = "hashicorp/bionic64"
  #   node2.vm.hostname = "Kube-node2"
  #   node2.vm.provider "virtualbox" do |v|
  #     v.name = "Kube_node2"
  #   end
  #   node2.vm.provision "docker" do |d|
  #   end
  #   node2.vm.provision :shell, path: "bootstrap.sh"
  #   node2.vm.network "public_network", ip: "192.168.1.210", bridge: 'Intel(R) Wireless-AC 9560 160MHz'
  # end

end
